FROM php:5.6-apache

#&& sed -i 's!/var/www/html!/var/www/public!g' /etc/apache2/sites-available/000-default.conf \
#&& mv /var/www/html /var/www/public \

RUN apt-get update \
 && apt-get install -y php5.6-xdebug \
 && a2enmod rewrite \
 && sed -i 's!/#ServerName www.example.com:80!#ServerName localhost:80!g' /etc/apache2/sites-available/000-default.conf \
 && echo "AllowEncodedSlashes On" >> /etc/apache2/apache2.conf

WORKDIR /var/www/html
